### ISSUE TITLE
kudos for the boilprate small question

### ISSUE THREAD

**Issue by shevetonline** [awurth/Slim#3]
i liked the combination of simantic and slim your thinking is unique it helped me build and advance

i'm a deaf and blind computer programmer using briale display

as i am  new to slim and have manged to build on its basic skeleton tutoria project app as i learned it
so i tried doing the same with your structure it seems a bit complicated...
 took your project as a tutorial for my own learning curve
added routes and pages 
facing diffuclty with adding an admin view
 only enabled checking the auth.check() using the twig %if% to see if user is logged and in session
wanted to build as first step an admin only interface using the premissions to view\edit\delete users 
i was unable to do so since lacking some wiki about the structure
any basic guide wiki would be much thanked for

[src.zip](https://github.com/awurth/slim-base/files/1333443/src.zip)

**Comment by awurth** [comment]
Hi. Glad you liked my work. Since there are very few people who are downloading the boilerplate, I didn't write any documentation about it, I will fix this soon.

I don't really understand what you want me to explain about your admin interface: is it the authentication system, or how to organize your files?

If I had to create an Admin area, I would copy the structure of the `src/App` folder into `src/Admin` (don't forget to update your `composer.json` to update the autoloader) and use a Middleware to check if the user has admin rights, applied on all routes of your admin interface. You can use `src/App/Middleware/AuthMiddleware.php` as a model and just add a check on the user role.

**Comment by shevetonline** [comment]
hi
yes... since you created roles od admin and privlieges
i was trying to create an interface that only the admin could eneter
the src/admin directory sounds right it fits your boilprate 
a good idea is the wiki
i am still learning the code of your boilprate
and trying to implement the routes and contents separtion between admin role and user pages
any help would be appreciated

**Comment by awurth** [comment]
Sorry for responding so late, I'm really busy right now with finding a job.

I've created a wiki here: https://github.com/awurth/slim-base/wiki
There's not much in there for now but I will complete it as soon as I can.

**Comment by shevetonline** [comment]
looking much better
saw the security
strating to grasp it better thanks for the wiki i am progressing in your structure as you continue
what kind of a job are you going for??

**Comment by awurth** [comment]
I just finished my studies and am looking for work as a Backend/Fullstack Web Developer.

Also, version 3 of slim-base will be out soon and will come with major changes in the structure as well as an Admin section as this is a common feature.

**Comment by elshobokshy** [comment]
I do use your boilerplate too, as well as many others I believe. There's not many good slim boilerplates out there, so thank you for creating it.

**Comment by awurth** [comment]
You're welcome! Glad my work is appreciated :)
