### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by elshobokshy** [awurth/Slim#9]
The code now forces us to have PHP 7.1 to use it, as Symfony's Dotenv isn't compatible with PHP 7.0, so why is there that Dotenv ? What is it's use? There is no official PHP 7.1 on linux yet so...

**Comment by awurth** [comment]
Actually Symfony Dotenv v3.* requires PHP >=5.5.9 or >=7.0.8. The problem comes from the `composer.lock`, because I'm working with PHP 7.2 so composer downloaded the latest version of the packages.

I made some tests with PHP 7.0 but wasn't able to identify which package was involved so I just deleted the `composer.lock` file.

**Comment by elshobokshy** [comment]
Thanks! :D
